-- Fake inserts. All scripts were generated by Claude

INSERT INTO customers (customer_id, first_name, last_name, email, birth_date, country_code, is_active)
SELECT
    gen_random_uuid(),
    (ARRAY['Олексій','Марія','Іван','Анна','Дмитро','Олена','Сергій','Тетяна','Михайло','Наталія',
            'Андрій','Юлія','Василь','Ірина','Павло','Оксана','Роман','Людмила','Денис','Галина'])[floor(random()*20+1)],
    (ARRAY['Коваленко','Шевченко','Бойко','Мельник','Павленко','Лисенко','Гриценко','Романенко',
            'Савченко','Кравченко','Мороз','Кузьменко','Поліщук','Ткаченко','Марченко'])[floor(random()*15+1)],
    'user' || g || '@' || (ARRAY['gmail.com','ukr.net','outlook.com'])[floor(random()*3+1)],
    CURRENT_DATE - (random() * 20000 + 6570)::INTEGER,
    'UKR',
    true
FROM generate_series(1, 50) g;


INSERT INTO accounts (account_id, customer_id, account_number, currency, balance, status)
SELECT
    gen_random_uuid(),
    customer_id,
    'UA' || floor(random()*90+10)::TEXT || '3996220000' || lpad(row_number() OVER ()::TEXT, 16, '0'),
    ((ARRAY['UAH','UAH','UAH','USD','EUR'])[floor(random()*5+1)])::currency_enum,
    round((random() * 499000 + 1000)::NUMERIC, 2),
    ((ARRAY['ACTIVE','ACTIVE','ACTIVE','ACTIVE','FROZEN','CLOSED'])[floor(random()*6+1)])::account_status_enum
FROM customers
CROSS JOIN generate_series(1, 2);


INSERT INTO cards (card_id, account_id, card_number_hash, card_type, status, expiration_date)
SELECT
    gen_random_uuid(),
    account_id,
    md5(account_id::TEXT || generate_series::TEXT),
    (ARRAY['VISA','MASTERCARD','AMEX'])[floor(random()*3+1)],
    ((ARRAY['ACTIVE','ACTIVE','ACTIVE','BLOCKED','EXPIRED'])[floor(random()*5+1)])::card_status_enum,
    CURRENT_DATE + (random() * 1825)::INTEGER
FROM accounts
CROSS JOIN generate_series(1, 2)
WHERE status = 'ACTIVE';


INSERT INTO transactions (transaction_id, account_id, card_id, amount, currency, merchant_category, merchant_country, transaction_at)
SELECT
    gen_random_uuid(),
    a.account_id,
    (SELECT card_id FROM cards WHERE account_id = a.account_id AND status = 'ACTIVE' ORDER BY random() LIMIT 1),
    CASE
        WHEN random() < 0.10 THEN round((random() * 500000 + 400000)::NUMERIC, 2)
        WHEN random() < 0.25 THEN round((random() * 95000 + 5000)::NUMERIC, 2)
        ELSE round((random() * 49900 + 100)::NUMERIC, 2)
    END,
    a.currency,
    ((ARRAY['GROCERY','RESTAURANT','ELECTRONICS','CLOTHING','MEDICAL','TRAVEL','ONLINE','FUEL','TRANSFER','ATM'])[floor(random()*10+1)])::VARCHAR,
    CASE
        WHEN random() < 0.15 THEN (ARRAY['RUS','BLR','IRN','PRK','SYR'])[floor(random()*5+1)]
        ELSE (ARRAY['UKR','UKR','UKR','USA','DEU','FRA','GBR','POL'])[floor(random()*8+1)]
    END,
    NOW() - (random() * 365 * interval '1 day') +
    CASE
        WHEN random() < 0.15 THEN (floor(random()*3+2) * interval '1 hour')
        ELSE (floor(random()*14+8) * interval '1 hour')
    END
FROM accounts a
CROSS JOIN generate_series(1, 10)
WHERE a.status = 'ACTIVE'
LIMIT 1000;


SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM accounts;
SELECT COUNT(*) FROM cards;
SELECT COUNT(*) FROM transactions;
SELECT COUNT(*) FROM fraud_alerts;
